databases:
  - name: strive_backend
    databaseName: strive_backend
    user: strive_backend

services:
  - type: web
    name: strive_backend
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: BUNDLE_VERSION
        value: 2.2.3
      - key: RUBYOPT
        value: "--disable=gem"
      - key: DATABASE_URL
        fromDatabase:
          name: strive_backend
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false